services:
  mongodb:
    image: mongo
    # ports:
    #   - "27017:27017"
    volumes:
      - mongo-data:/data/db
      # - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    restart: unless-stopped


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "npm run build && npm run start"
    ports:
      - "3456:3456"
    env_file:
      - .env.docker
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/moodle-system
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_API_URL=http://backend:3456
    depends_on:
      - mongodb
      - backend
    restart: unless-stopped

  init-service:
    image: alpine:3.21.3
    volumes:
      - ./backend:/app
    working_dir: /app
    env_file:
      - .env.docker
    depends_on:
      - backend
    command: >
      sh -c "
        echo 'Waiting for backend to be ready...' &&
        sleep 3
        apk add --no-cache curl &&
        chmod +x ./setup_initial_data.sh &&
        sh ./setup_initial_data.sh
      "
    restart: "no"

volumes:
  mongo-data: